build_dso: Take package_dir into account
package_dir needs to be taken into account for inplace builds, because
then inplace directory of a package != directory of the package when it
is installed. For example setuptools_dso itself uses
`package_dir={'':'src'}` in its setup.py and this way for inplace build the
directory of setuptools_dso package is not setuptools_dso/ but
src/setuptools_dso/ instead.

However `build_dso --inplace` was installing built libraries without
taking package_dir into account. For example with amended example/ test,
libdemo.so was installed into dsodemo/lib/libdemo.so instead of
src/dsodemo/lib/libdemo.so, while dtest.so was correctly installed into
src/dsodemo/ext/dtest.so . As the result it was not working:

    + python -m dsodemo.cli
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/kirr/src/tools/py/pypa/setuptools_dso/example/src/dsodemo/cli.py", line 15, in <module>
        from .ext import dtest
    ImportError: libdemo.so.1.0: cannot open shared object file: No such file or directory
    .../setuptools_dso$ ll example/
    итого 16
    drwxr-xr-x 4 kirr kirr 4096 дек  4 18:12 build
    drwxr-xr-x 3 kirr kirr 4096 дек  4 18:12 dsodemo
    -rwxr-xr-x 1 kirr kirr  639 дек  4 18:12 setup.py
    drwxr-xr-x 3 kirr kirr 4096 дек  4 18:06 src
    .../setuptools_dso$ ll example/dsodemo/lib/
    итого 136
    -rwxr-xr-x 1 kirr kirr 68888 дек  4 18:12 libdemo.so
    -rwxr-xr-x 1 kirr kirr 68888 дек  4 18:12 libdemo.so.1.0
    .../setuptools_dso$ ll example/src/dsodemo/ext/
    итого 124
    -rwxr-xr-x 1 kirr kirr 119000 дек  4 18:12 dtest.so
    -rw-r--r-- 1 kirr kirr      0 июл 30 21:37 __init__.py
    -rw-r--r-- 1 kirr kirr    110 дек  4 18:12 __init__.pyc
    .../setuptools_dso$ ldd example/src/dsodemo/ext/dtest.so
            linux-vdso.so.1 (0x00007fffae3fd000)
            libdemo.so.1.0 => not found
            libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1c3bf20000)
            libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1c3bd9d000)
            libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1c3bd83000)
            libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1c3bd62000)
            libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1c3bba1000)
            /lib64/ld-linux-x86-64.so.2 (0x00007f1c3c149000)
    .../setuptools_dso$ objdump -x example/src/dsodemo/ext/dtest.so |grep PATH
      RUNPATH              \$ORIGIN/../lib:$ORIGIN/../lib

-> Fix it by taking package_dir option into account in --inplace dsocmd handler.

Note1: The code to do so mimics build_ext from setuptools:

    https://github.com/pypa/setuptools/blob/v42.0.2-0-g1d03fdc9/setuptools/command/build_ext.py#L89-L107

Note2: Sources of Extension and DSO are specified with full path from project
top-level, because it already works this way for unmodified Extension even in
presence of package_dir.